name: Main

on:
  push:
    tags:
      - "*.*.*"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Checkout
      uses: actions/checkout@v3
    - name: zip
      run: mkdir rigify_helpers && rsync -av --exclude='.git/' --exclude='.screenshots/' --exclude='.github/' --exclude='rigify_helpers/' . rigify_helpers/ && zip -r ${{ github.event.repository.name }}-${{ env.RELEASE_VERSION }}.zip rigify_helpers/
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: ${{ github.event.repository.name }}-${{ env.RELEASE_VERSION }}.zip
